##############################
# 스프링 부트 설정 파일
##############################


# 서버 설정
server:
  port: 7070
  #address: 127.0.0.1

spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "0000"



