
spring:
  application:
    name: boardserver
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
  profiles:
    include: log4j2
    active: develop

mybatis:
  # @Alias 를 스캔하는 경로를 설정합니다. 아래 형식은 프로젝트의 전체를 스캔합니다.
  # mapper 에서 해당 패키지명 생략 후, 작성 가능
  type-aliases-package: sudapapa.java.boardserver
  #  mapper 파일의 경로를 지정합니다. 아래 형식은 mapper 디렉토리 하위의 모든 xml 파일을 포함합니다.
  # classpath 는 resource 폴더
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # db 컬럼명에서 언더바를 제거한 카멜케이스로 변경하여 리턴합니다.
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
    default-statement-timeout: 25
  config-location: classpath:config/mybatis-config.xml



